<a href="https://colab.research.google.com/github/Swapnil-nhsrcl/brightmart-media-survey/blob/main/BRIGHTMART_MEDIA_CASE_STUDY_CODING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # IMPORTING CSV FILES

In [ ]:
df=pd.read_csv('/content/Advertising (1).csv') # ASSGNING VARIABLE df TO FILE ADVERTI

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Advertising (1).csv",index_col=0)

In [ ]:
df

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
X=df.drop('Sales',axis=1)
y=df['Sales']

In [ ]:
df

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
X

        TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [ ]:
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ...
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: Sales, Length: 200, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

# Split the dataset into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (160, 3)
X_test shape: (40, 3)
y_train shape: (160,)
y_test shape: (40,)

In [ ]:
from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
model = LinearRegression()

# Fit the model on the training data
model.fit(X_train, y_train)

# Print the intercept and coefficients
print(f"Intercept: {model.intercept_}")
for col, coef in zip(X_train.columns, model.coef_):
    print(f"{col} Coefficient: {coef}")

Intercept: 2.9790673381226256
TV Coefficient: 0.044729517468716326
Radio Coefficient: 0.1891950542343766
Newspaper Coefficient: 0.0027611143413672056

In [ ]:
model.predict([[20,12,5]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([6.15780391])

In [ ]:
model.score(X_test,y_test)

0.899438024100912

In [ ]:
from sklearn.model_selection import cross_val_score
import numpy as np

# Perform 5-Fold Cross Validation on the test set
scores = cross_val_score(model, X_test, y_test, cv=5)

print(f"Cross-Validation $R^2$ Scores (5 Folds): {scores}")
print(f"Mean $R^2$ Score: {scores.mean():.4f}")
print(f"Standard Deviation: {scores.std():.4f}")

Cross-Validation $R^2$ Scores (5 Folds): [0.92614766 0.32379136 0.93091358 0.8127582  0.88011515]
Mean $R^2$ Score: 0.7747
Standard Deviation: 0.2294

In [ ]:
from sklearn.model_selection import cro

#

ImportError: cannot import name 'cro' from 'sklearn.model_selection' (/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/__init__.py)

In [ ]:
from sklearn.model_selection import cro

# Perform 5-Fold Cross Validation on the test set
scores = cross_val_score(model, X_test, y_test, cv=4)

print(f"Cross-Validation $R^2$ Scores (5 Folds): {scores}")
print(f"Mean $R^2$ Score: {scores.mean():.4f}")
print(f"Standard Deviation: {scores.std():.4f}")

ImportError: cannot import name 'cro' from 'sklearn.model_selection' (/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/__init__.py)

In [ ]:
model.score(X_test,y_test)

0.899438024100912

In [ ]:
model.score(X_trIN,y_train)

NameError: name 'X_trIN' is not defined

In [ ]:
model.score(X_train,y_train)

0.8957008271017817

In [ ]:
from sklearn.model_selection import cross_val_score

# Perform 5-Fold Cross Validation on the test set
scores = cross_val_score(model, X_test, y_test, cv=4)

print(f"Cross-Validation $R^2$ Scores (5 Folds):", scores)
print(f"Mean $R^2$ Score:, {scores.mean():4f}")
print(f"Standard Deviation, {scores.std():4f}")

Cross-Validation $R^2$ Scores (5 Folds): [0.90825305 0.80989255 0.8976876  0.86114857]
Mean $R^2$ Score:, 0.869245
Standard Deviation, 0.038467

In [ ]:
import joblib
# Save the model first to ensure it's up to date
joblib.dump(model, 'model.sav')

# Create app.py
app_code = """import streamlit as st
import joblib
import numpy as np

# Load the saved model
model = joblib.load('model.sav')

st.set_page_config(page_title="Advertising Sales Predictor", layout="centered")

st.title("📈 Advertising Sales Prediction App")
st.write("Enter the budget for each advertising channel to predict the expected Sales.")

# Inputs for TV, Radio, and Newspaper
TV = st.number_input("TV Budget ($)", min_value=0.0, max_value=1000.0, value=100.0, step=1.0)
Radio = st.number_input("Radio Budget ($)", min_value=0.0, max_value=1000.0, value=20.0, step=1.0)
Newspaper = st.number_input("Newspaper Budget ($)", min_value=0.0, max_value=1000.0, value=10.0, step=1.0)

# When the user clicks the button, make the prediction
if st.button("Predict Sales"):
    features = np.array([[TV, Radio, Newspaper]])
    prediction = model.predict(features)[0]
    st.success(f"🎯 Predicted Sales: {prediction:.2f} units")
"""

with open('app.py', 'w') as f:
    f.write(app_code)

# Create requirements.txt
requirements_code = """streamlit
scikit-learn
joblib
numpy
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements_code)

print("Successfully created app.py and requirements.txt!")

Successfully created app.py and requirements.txt!